# Generated by Django 2.1.4 on 2022-03-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeconfig',
            name='run_status',
            field=models.IntegerField(choices=[(0, '停止'), (1, '正常运行'), (2, '正在启动服务'), (3, '检测可用'), (4, '等待生成证书'), (5, '已生成证书')], default=0, verbose_name='运行状态'),
        ),
        migrations.AlterField(
            model_name='nodeconfig',
            name='status',
            field=models.IntegerField(choices=[(0, '不可用'), (1, '可用'), (2, '未开启')], default=2, verbose_name='连接状态'),
        ),
    ]
