# Generated by Django 2.1.4 on 2022-03-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_auto_20220323_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeconfig',
            name='domain_id',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='域名ID'),
        ),
        migrations.AddField(
            model_name='nodeconfig',
            name='ssl_id',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='证书ID'),
        ),
        migrations.AlterField(
            model_name='nodeconfig',
            name='run_status',
            field=models.IntegerField(choices=[(0, '停止'), (1, '正常运行'), (2, '正在启动服务'), (3, '检测可用'), (4, '已生成域名'), (5, '等待生成证书'), (6, '已生成证书')], default=0, verbose_name='运行状态'),
        ),
    ]
