# Generated by Django 2.1.4 on 2022-03-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_auto_20220324_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeconfig',
            name='info',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='信息'),
        ),
        migrations.AlterField(
            model_name='nodeconfig',
            name='run_status',
            field=models.IntegerField(choices=[(0, '停止'), (1, '正常运行'), (2, '正在启动服务'), (3, '检测可用'), (4, '已生成域名'), (5, '已生成证书'), (6, '正在关闭服务')], default=0, verbose_name='运行状态'),
        ),
    ]
