
# Generated by Django 2.1.4 on 2022-03-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_auto_20220325_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeconfig',
            name='cname_validation_p1',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='cname_p1'),
        ),
        migrations.AddField(
            model_name='nodeconfig',
            name='cname_validation_p2',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='cname_p2'),
        ),
    ]
