# Generated by Django 2.1.4 on 2022-03-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0005_auto_20220328_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='english_name',
            field=models.CharField(db_index=True, default='', max_length=128, verbose_name='英语国家'),
        ),
        migrations.AddField(
            model_name='region',
            name='english_name',
            field=models.CharField(db_index=True, default='', max_length=128, verbose_name='英语地区'),
        ),
    ]
