# Generated by Django 2.1.4 on 2022-03-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0006_auto_20220330_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeconfig',
            name='old_instance_id',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='等待删除实例ID'),
        ),
    ]
