# Generated by Django 2.1.4 on 2022-06-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0007_nodeconfig_old_instance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajonnode',
            name='test_black',
            field=models.TextField(blank=True, default='', null=True, verbose_name='黑名单 测试'),
        ),
        migrations.AddField(
            model_name='trajonnode',
            name='test_white',
            field=models.TextField(blank=True, default='', null=True, verbose_name='白名单 测试'),
        ),
    ]
