# Generated by Django 2.1.4 on 2022-06-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0008_auto_20220628_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajonnode',
            name='hide_switch',
            field=models.IntegerField(choices=[(1, '开'), (0, '关')], default=0, verbose_name='是否隐藏'),
        ),
    ]
