# Generated by Django 2.1.4 on 2022-06-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0009_trajonnode_hide_switch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajonnode',
            name='hide_switch',
        ),
    ]
