# Generated by Django 2.1.4 on 2022-07-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0014_nodeconfig_test_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeconfig',
            name='test_status',
            field=models.IntegerField(blank=True, choices=[(0, '不可用'), (1, '测试通过'), (2, '测试失败')], default=0, null=True, verbose_name='测试状态'),
        ),
    ]
