# Generated by Django 2.1.4 on 2022-07-07 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0015_auto_20220701_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='组名称')),
                ('image_url', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='icon')),
            ],
        ),
        migrations.AlterField(
            model_name='nodeconfig',
            name='run_status',
            field=models.IntegerField(choices=[(0, '停止'), (1, '正常运行'), (2, '正在启动服务'), (3, '检测可用'), (4, '已生成域名'), (5, '已生成证书'), (6, '正在关闭服务'), (9, '节点测试')], default=0, verbose_name='运行状态'),
        ),
        migrations.AddField(
            model_name='trajonnode',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='node.NodeGroup', verbose_name='节点分组'),
        ),
    ]
