# Generated by Django 2.1.4 on 2022-07-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0016_auto_20220707_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceDel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='实例id')),
                ('main_ip', models.CharField(blank=True, db_index=True, default=None, max_length=128, null=True, verbose_name='ip')),
            ],
            options={
                'verbose_name': '实例配置',
                'verbose_name_plural': '实例配置',
            },
        ),
        migrations.AlterModelOptions(
            name='nodegroup',
            options={'verbose_name': '节点分组', 'verbose_name_plural': '节点分组'},
        ),
    ]
