# Generated by Django 2.1.4 on 2022-07-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0017_auto_20220708_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeconfig',
            name='instance_status',
            field=models.IntegerField(blank=True, choices=[(0, '正常'), (1, '5次黑名单')], default=0, null=True, verbose_name='测试状态'),
        ),
    ]
