# Generated by Django 2.1.4 on 2022-07-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0018_nodeconfig_instance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajonnode',
            name='script_status',
        ),
        migrations.AlterField(
            model_name='nodeconfig',
            name='run_status',
            field=models.IntegerField(choices=[(0, '停止'), (1, '正常运行'), (2, '正在启动服务'), (3, '检测可用'), (4, '已生成域名'), (5, '已生成证书'), (6, '正在关闭服务'), (9, '节点测试'), (10, '申请失败')], default=0, verbose_name='运行状态'),
        ),
        migrations.AlterField(
            model_name='trajonnode',
            name='download',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='下载测速(单位:MB)'),
        ),
    ]
